README.md
api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironicconductor_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
config/samples/ironic_v1beta1_ironic.yaml
config/samples/ironic_v1beta1_ironic_standalone.yaml
controllers/ironic_controller.go
controllers/ironicconductor_controller.go
pkg/ironicconductor/service.go
pkg/ironicconductor/statefulset.go
templates/ironic/bin/pxe-init.sh
templates/ironic/config/dnsmasq.conf
templates/ironic/config/ironic.conf

For now NetworkAttachmentDefinition needs to be manually defined, and
the same name used in ProvisionNetwork to expose boot services to an
external interface.
Ideally another operator will take the responsiblity of managing all
NetworkAttachmentDefinition resources (ovs-operator has similar
requirements).

Use ProvisionNetwork to specify an additional network

---

api/bases/ironic.openstack.org_ironicapis.yaml
api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicconductor_types.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml

When a CRD has an optional struct field the defaulting of that field needs special care. Both the field with the struct type need a full default value defined and each individual subfields in the struct needs default value defined. Otherwise in the first reconcile call the PasswordSelectors is empty and then in the second reconcile it is filled.
Now documented via https://github.com/openstack-k8s-operators/docs/pull/12

Fix defaulting PasswordSelectors

---

api/bases/ironic.openstack.org_ironicapis.yaml
api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicconductor_types.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
controllers/ironic_controller.go

Users should be able to define a nodeSelector at the top level and override it for any individual CR. If it's not changed in individual CR's, it should default to the top level nodeSelector.

Add handling for top level NodeSelector

---

controllers/ironic_controller.go

Ever since  : https://github.com/openstack-k8s-operators/lib-common/pull/87
Podified operators which use service dbs and the db.CreateOrPatchDB method , now will get the finalizer set on the db automatically when using the newest lib-common, but they won't have the code remove it on cleanup i.e reconcileDelete, which might make the delete operator action hang.
This adds the service Db removal code in the operator delete (reconcileDelete) function to work with the above.
Also updated lib-common to latest as to not break lib-common's exported functions

add_service_db_finalizer_logic

---

controllers/ironic_controller.go
templates/ironic/config/ironic.conf

The [keystone_authtoken] www_authenticate_uri option should point public endpoint instead of internal endpoint, because the uri is returned to clients when authentication fails.

Use public endpoint for www_authenticate_uri

---

api/go.mod
api/go.sum
controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
go.mod
go.sum

Introduces the use of `lib-common`'s `PatchIntstance()` func and attempts to remove instance-update race condition concerns

Use new lib-common 'PatchInstance' pattern

---

controllers/ironic_controller.go
pkg/ironicconductor/statefulset.go

When using "oslo" transport we should not probe the json-rpc port 8089. The probe fails and the container keeps restarting.

Only probe JSON-RPC port when use json-rpc transport

---

pkg/ironic/initcontainer.go
templates/ironic/bin/conductor-init.sh

Building esp.img with mtools means mount isn't required, which means the conductor init container no longer needs to run as a privileged container.
This is the same mtools recipe used in the metal3 image[1]
[1] https://github.com/metal3-io/ironic-image/blob/main/prepare-efi.sh#L37-L44

Build esp.img with mtools, drop privileged from init container

---

templates/ironic/config/ironic.conf

The default value is /usr/lib/syslinux/isolinux.bin which is different to what the syslinux-nonlinux package installs.
This file won't exist until this dependency change[1] reaches the container image.
[1] https://review.rdoproject.org/r/c/openstack/ironic-distgit/+/46663

Correctly configure [DEFAULT]isolinux_bin

---

controllers/ironic_controller.go

Let's keep the ServiceUser for Inspector separate like we used to with TripleO?
```
+----------------------------------+------------------+
| ID                               | Name             |
+----------------------------------+------------------+
| f2c959795e7841ecb51f25ab6d7a177a | ironic           |
| a71fc9ce71ae4de6a9cf3f6a32407cb6 | ironic-inspector |
+----------------------------------+------------------+
```

Don't pass ServiceUser to Inspector

---

controllers/ironic_controller.go

It does not work, the `DatabaseUser` is actually not configurable in the mariadb-operator ... the user defaults to `.DatabaseName`.
See: https://raw.githubusercontent.com/openstack-k8s-operators/mariadb-operator/master/templates/database.sh

Don't pass DatabaseUser from ironic to inspector

---

controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go

The current logic ignores the error but it should be returned so that the error can be detected in the reconciler.

Return error in ConfigMap creation

---

config/rbac/role.yaml
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
pkg/ironicconductor/service.go
pkg/ironicinspector/service.go
pkg/ironicinspector/statefulset.go

Add RBAC rules to allow the operator to get and list
```
apiGroups: operator.openshift.io
resources: ingresscontrollers
```
Add `GetIngressDomain()` method to inspector and conductor contollers. This method uses an unstructored object to get the default openshift-ingress-operator IngressController and parses the result to get the ingressDomain.
Since the ingressDomain is resolved prior to creating statefulsets and routes we no longer need to requeue to to inject the IngressDomain.

Get Ingress Domain from API

---

controllers/ironic_controller.go

Was returning `nil` instead of the actual error in such a situation

Fix gen CM error return

---

api/bases/ironic.openstack.org_ironicinspectors.yaml
api/v1beta1/ironicinspector_types.go
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go

Inspector status:
Adds requeue if inspector ReadyCount is 0, if we don't do that
the reconcile loop end's without setting proper statuses.
APIEndpoints+ServiceIDs:
Uses a for range loop to merge the maps instead of reassigning
the entire map.
Also initilaze maps with make(), doing so resolves:
`panic: assignment to entry in nil map` issues.
Also add's some RequeueAfter time.

Fix Inspector status and APIEndpoints+ServiceIDs

---

controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
pkg/ironic/funcs.go

Instead of duplicate implementations of GetIngressDomain in each controller add a shared function in pkg/ironic/funcs.go that can be used by both conductor and inspector controllers.
Also adds error handling.

Move GetIngressDomain to pkg/ironic/funcs.go

---

pkg/ironicconductor/statefulset.go
pkg/ironicinspector/statefulset.go

Default oslo.service graceful_shutdown_timeout is 60, so align with that

Set TerminationGracePeriodSeconds on statefulsets

---

.github/workflows/build-ironic-operator.yaml

We are hitting rate-limt during post merge image build:
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
It seems it is coming from [1] and can be fixed by passing the GITHUB_TOKEN there. So this patch does that to avoid build failures due to rate-limit.
[1] https://github.com/kubernetes-sigs/kustomize/blob/0fd385d7197026b92272dc8688ec66593be91fba/hack/install_kustomize.sh#L145

Pass GITHUB_TOKEN to install_kustomize.sh to avoid rate-limit

---

.github/workflows/build-ironic-operator.yaml

We build containers and push to registry in post merge. Not building container for each hash can cause issue becuase of missing container tags, and pin-custom-bundle-dockerfile.sh can't match the git $REF with any /ironic-operator-bundle image tag.

Drop paths-ignore from build operator workflow

---

api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
api/v1beta1/ironicconductor_types.go
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
config/samples/ironic_v1beta1_ironic.yaml
config/samples/ironic_v1beta1_ironic_conductor_groups.yaml
config/samples/ironic_v1beta1_ironic_standalone.yaml
controllers/ironic_controller.go

Add storageClass to Ironic CRD and pass the value
to IronicConductor if storageClass is not defined
in the conductor spec.
This should allow use of "STORAGE_CLASS" variable
with install_yamls Makefile/kustomization while
still giving the option to override storageClass
per "conducto group".
Jira: [OSP-22470](https://issues.redhat.com//browse/OSP-22470)

Add storageClass for Ironic CRD

---

api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
config/crd/bases/ironic.openstack.org_ironics.yaml

This would allow us to use the storageClass from parent (openstack-operator).

Provide default for storageClass

---

api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironicinspectors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/go.mod
api/v1beta1/ironic_types.go
api/v1beta1/ironic_webhook.go
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
go.mod
pkg/ironic/funcs.go

* Validate that each DHCP Range has sane value IP addresses valid, start/end/gateway in same range
* Validates DHCP start->end ranges does not overlap
Also:
* Changes the DHCPRange struct to include a `cidr` field.
* The `netmask` and `prefix` fields changed to be hidden fields.
* `netmask` and `prefix` are set internally prior to passing the dhcpRanges to tempalteParameters, sourcing the info from the `cidr` value.
* `cidr`, `start` and `end` changed to mandatory (required)
Example validation errors:
```
The Ironic "ironic" is invalid:
* spec.ironicConductors[0].dhcpRanges[0].gateway: Invalid value: "172.25.22.1": address not in IP address prefix (CIDR) 172.25.23.0/24
* spec.ironicInspector.dhcpRanges[0].end: Invalid value: "172.25.23.777": not an IP address
```
```
The Ironic "ironic" …
```

webhook - validatate dhcpRanges

---

api/bases/ironic.openstack.org_ironicinspectors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironicinspector_types.go
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
controllers/ironic_controller.go
pkg/ironicinspector/statefulset.go

Inspector creates it's own database and derives the hostname from the results we should get `DatabaseHostname` from Status when setting `initContainerDetails`.

Remove DatabaseHostname from inspector SPEC

---

controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go

Set owner reference for conductor services and routes to the statuful set Pod. This ensures that garbage collection will delete services and routes when the statefulset is scaled down.    
Unfortunately the the route and service packages in lib-common does not allow this level of control.
Jira: [OSP-22519](https://issues.redhat.com//browse/OSP-22519)

Make Services and Routes owned by Pod - fixes garbage collect on scaling

---

api/bases/ironic.openstack.org_ironicinspectors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
api/v1beta1/ironicinspector_types.go
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
controllers/ironic_controller.go

* Set validation to Maximum=1 for replicas 
We have decided not to support HA/Scaling for the inspector service.
In other words - rely on kubernets to service availability.
* Don't create inspector deployment if replicas count is 0.
* Delete the inspector deployment if scaled to 0.
Jira: [OSP-22518](https://issues.redhat.com//browse/OSP-22518)

Ironic inspector scaling - Maximum 1 replica

---

Makefile

Cross checked in keystone-operator, it should be golangci-lint and not tolangci-lint.
[1] https://github.com/openstack-k8s-operators/keystone-operator/blob/master/Makefile#L116 
test -s $(LOCALBIN)/golangci-lint

fix typo in golangci-lint name

---

controllers/ironic_controller.go
controllers/ironicconductor_controller.go

Mark ExposeServiceReady for "Ironic" True if both IronicAPI and Inspector heve ExposeServiceReady == True.
Mark DeoploymentReady for "Ironic" True if all Conductor groups and Inspector have DeoploymentReady == True.
We initialize conditions that we then never use, removing:
* KeystoneReadyCondition in conductor controller
* Expose service condition from conductor
* BootstrapReady condition from ironic controller

Clean up conditions

---

pkg/ironic/dbsync.go
pkg/ironicinspector/dbsync.go

... instead hard-coding the string in our own logic.

Use constant to define restart policy

---

pkg/ironic/initcontainer.go
pkg/ironicinspector/initcontainer.go
templates/common/bin/get_net_ip

Annotation `k8s.v1.cni.cncf.io/networks-status` has been changed to `k8s.v1.cni.cncf.io/network-status` and the former is no longer supported [1]
[1] https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/pull/45

Change references of networks-status to network-status

---

tests/kuttl/common/assert-sample-deployment.yaml

The generation field will update everytime the resource is updated so we cannot and should not validate the value of this field
Change-Id: I413df4623289a6a69afa61c3d0f190434e155ee4

Remove generation field from deployment assertion

---

tests/kuttl/common/assert-sample-deployment.yaml

https://github.com/openstack-k8s-operators/ironic-operator/pull/159 removed the admin endpoints for ironic and ironic-inspector so removing those tests
Change-Id: I0808b265a744bd594689e07c6f642807721003e9

Remove admin endpoint tests

---

pkg/ironic/initcontainer.go
pkg/ironic/volumes.go
pkg/ironicinspector/initcontainer.go
pkg/ironicinspector/volumes.go
templates/common/bin/get_net_ip

In some cases the annotations are not ready.
By using a volume we can add retrying logic in `get_net_ip` script.
Jira: [OSP-23573](https://issues.redhat.com//browse/OSP-23573)

Use volume for DownwardAPI - network-status

---

README.md
api/bases/ironic.openstack.org_ironicapis.yaml
api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironicinspectors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
api/v1beta1/ironic_webhook.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicconductor_types.go
api/v1beta1/ironicinspector_types.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
config/samples/ironic_v1beta1_ironic.yaml
config/samples/ironic_v1beta1_ironic_conductor_groups.yaml
config/samples/ironic_v1beta1_ironic_standalone.yaml
controllers/ironic_controller.go
controllers/ironicinspector_controller.go
pkg/ironic/dbsync.go
pkg/ironic/initcontainer.go
pkg/ironicapi/deployment.go
pkg/ironicconductor/statefulset.go
pkg/ironicinspector/dbsync.go
pkg/ironicinspector/initcontainer.go
pkg/ironicinspector/statefulset.go
templates/ironic/bin/init.sh
templates/ironicinspector/bin/init.sh
tests/kuttl/common/assert-sample-deployment.yaml

It is currently implemented in lib-common, but not in mariadb-operator. mariadb-operator always creates database user with name == .DatabaseName.
Whith this change we pass the same value (the database name) to lib-common's NewDatabase function.
See: https://raw.githubusercontent.com/openstack-k8s-operators/mariadb-operator/master/templates/database.sh

Remove DatabaseUser from all resource specs

---

templates/ironic/config/httpboot-httpd.conf
templates/ironic/config/ironic-api-httpd.conf
templates/ironicinspector/config/httpboot-httpd.conf

... so that api can be accessed even when IPv6 is used for pod networks.

Bind all available addresses instead of 0.0.0.0

---

controllers/ironicconductor_controller.go
pkg/ironicconductor/statefulset.go
templates/common/config/ironic.conf

Fix deployHTTPURL:
This aligns with what inspector does now, ".apps" is already in
PodNamespace so it is not required here.
Standalone: set ironic API endpoint override:
This is required for deployment for heartbeat, etc.
This has been confirmed to work when there is no provisioning network.
To get this working when there is a provisioning network might require
more changes, since the ironic API needs to serve requests on the
provisioning network.

Fix deploy URLs for standalone

---

templates/common/bin/common.sh

This bug showed up after running for couple of days, when ipxe script is already in in /var/lib/config-data/merged/. The iPXE script is copied there by function merge_config_dir after the crudini so issue seen only on re-run.
Jira: [OSP-23943](https://issues.redhat.com//browse/OSP-23943)

merge_config_dir - no crudini on ipxe scripts

---

api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironicconductor_types.go
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml

Using the `json:"-" to "hide" the property cause issues, the generated config map using the values in the map end up with empty values. This might be caused by the json serialisation in the webhooks.
Let's just unhide the property, it may come in handy to expose them if we ever want to run conductor in a separate OCP cluster.
Jira: [osp-23942](https://issues.redhat.com//browse/osp-23942)

Unhide KeystoneVars

---

.golangci.yaml
.pre-commit-config.yaml
Makefile
hack/configure_local_webhook.sh
pkg/ironic/funcs.go

This PR replace deprecated go-linter using
revive (https://golangci-lint.run/usage/linters/#revive).
We will add "ginkgolinter" in follow up patch once we merged add pre-commit job in openshift/releases.
If we add "ginkgolinter" in this patch then it's causes below issue [1]
```
level=info msg="[config_reader] Config search paths: [./ /home/prow/go/src/github.com/openstack-k8s-operators/dataplane-operator /home/prow/go/src/github.com/openstack-k8s-operators /home/prow/go/src/github.com /home/prow/go/src /home/prow/go /home/prow /home /]"
level=info msg="[config_reader] Used config file .golangci.yaml"
level=error msg="Running error: unknown linters: 'ginkgolinter', run 'golangci-lint help linters' to see the list of supported linters"
```
This patch also Remove fmt dependency from make …

Add revive to golanci

---

tests/kuttl/tests/deployments/02-assert-deploy-ironic-conductor-groups.yaml

This was a carry over from the last PR.  The check for the null conductor group is valid because there is one deployed with no name.
Change-Id: I9bf98194744215b3d0642cc304a6b908b72511f0

Add null_conductor_group ReadyCount check

---

.github/workflows/golangci-lint.yaml

Now this operator is developed with golang 1.19 instead of 1.18, so we should use the correct version.

Use golang 1.19 in lint jobs

---

tests/kuttl/tests/deployments/01-deploy-ironic.yaml
tests/kuttl/tests/deployments/03-cleanup-ironic.yaml
tests/kuttl/tests/deployments/deploy/ironic_v1beta1_ironic.yaml
tests/kuttl/tests/deployments/deploy/kustomization.yaml

Following patterns established in https://github.com/openstack-k8s-operators/keystone-operator/pull/224
Change-Id: I65ca5347bfd3f04b3f4d17e7f59e6a7cb158299b

Remove depedency on install_yaml for resource creation

---

api/bases/ironic.openstack.org_ironicapis.yaml
api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironicinspectors.yaml
api/bases/ironic.openstack.org_ironicneutronagents.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
api/v1beta1/ironicneutronagent_types.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironicneutronagents.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
tests/kuttl/common/assert-sample-deployment.yaml

Ironic does not have separate bootstrap step and this flag is not actually used.

Remove unused boostrap debug flag

---

Makefile
README.md
config/default/manager_default_images.yaml
config/samples/ironic_v1beta1_ironic.yaml
config/samples/ironic_v1beta1_ironic_conductor_groups.yaml
config/samples/ironic_v1beta1_ironic_standalone.yaml
config/samples/ironic_v1beta1_ironicneutronagent.yaml
tests/kuttl/common/assert-sample-deployment.yaml
tests/kuttl/tests/deployments/02-assert-deploy-ironic-conductor-groups.yaml

We imported container build tools from TripleO as TCIB[1]. Now we are retiring TripleO and should complete the migration.
[1] https://github.com/openstack-k8s-operators/tcib

Replace TripleO images by TCIB images

---

api/v1beta1/ironic_webhook.go

ironic conductor and inspector types set a default for these, e.g they are never "" so the value defined fir the ironic parent never applies.
Remove the condition, and always set to what is defined for the parent.

Fix defaulting of RPCTransport and ServiceUser

---

tests/kuttl/common/assert-sample-deployment.yaml

Add a check to see if URL is set in status, if not set return code to 1 and sleep for 10 seconds (we are producing pages of logs while retrying these asserts).

Check to API endpoint exist before trying http req

---

api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/conditions.go
api/v1beta1/ironic_types.go
api/v1beta1/ironic_webhook.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/ironic.openstack.org_ironics.yaml
config/samples/ironic_v1beta1_ironic.yaml
config/samples/ironic_v1beta1_ironicneutronagent.yaml
controllers/ironic_controller.go

In ironic controller add deployment of ironic neutron agent. When replicas is ! > 0 the ironic neutron agent will not be deployed, setting replicas = 0 will also delete any running deployment.
Also:
* Update sample files to use zed container images for ironic neutron agent ... match the other components.
* Update description string for inspector
Jira: [OSP-24274](https://issues.redhat.com//browse/OSP-24274)

Add Deployment of ironic-neutron-agent

---

Makefile
api/bases/ironic.openstack.org_ironicneutronagents.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_webhook.go
api/v1beta1/ironicneutronagent_types.go
config/crd/bases/ironic.openstack.org_ironicneutronagents.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
config/default/manager_default_images.yaml
main.go

Set up the ironic webhook to default the image for ironic neutron agent the same way it works for the other container images.
Jira: [osp-24276](https://issues.redhat.com//browse/osp-24276)

Add ironic-neutron-agent image to ironicDefaults

---

controllers/ironic_controller.go

Initialize templateParameters["ConductorGroup"] with nil value in ironic controller. The ironic.conf template is shared between ironic controller and ironcconductor controller. Only the conductor controller uses ConductorGroup.

Initialize templateParameters["ConductorGroup"]

---

controllers/ironicinspector_controller.go

This seems to be the source of the current kuttl failure

Add template parameter KeystonePublicURL for inspector.conf

---

controllers/ironic_controller.go

Only the conductor config actually needs this in standalone mode, and that is already handled in the conductor controller.
Not discovering the actual endpoint saves an extra reconcile cycle, since this config is generated before IronicAPI is reconciled.

Set IronicPublicURL to empty string in ironic controller

---

config/samples/ironic_v1beta1_images.yaml
config/samples/ironic_v1beta1_ironic.yaml
config/samples/ironic_v1beta1_ironic_conductor_groups.yaml
config/samples/ironic_v1beta1_ironic_standalone.yaml
config/samples/ironic_v1beta1_ironicapi.yaml
config/samples/ironic_v1beta1_ironicconductor.yaml
config/samples/ironic_v1beta1_ironicinspector.yaml
config/samples/ironic_v1beta1_ironicneutronagent.yaml
config/samples/kustomization.yaml

- Remove namespace openstack, to align with other operators
- Ensure standalone and conductor groups samples have unique metadata
names so that kustomize will process them
- Remove image tags from all samples, defaults now come from the
operator environment
- Add a JSON6902 patch file which restates the image defaults.
It is provided as an example and for tooling to use it as a template
to convert to versioned tags.
- Add the image patch to kustomization.yaml, just for validation -
these samples are not bundled with the operator.
- Set the replicas attribute on the single service samples. They still
won't work but at least there is something valid.

Reorganize config samples

---

api/v1beta1/ironic_types.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicconductor_types.go
api/v1beta1/ironicinspector_types.go
api/v1beta1/ironicneutronagent_types.go
controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go
tests/functional/ironicneutronagent_controller_test.go

This ensures the Ready Condition is reset when CR becomes once ready but something fails during reconfiguration.

Reset Ready condition when update failed

---

api/bases/ironic.openstack.org_ironicapis.yaml
api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironicinspectors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicconductor_types.go
api/v1beta1/ironicinspector_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go

... because these fields are not really useful.

Remove Keystone service IDs from status fields

---

api/v1beta1/conditions.go
controllers/ironic_controller.go

This change makes sure that all conditions are initialized. Because of this change we have to mark true conditions for sub CRs such as IronicInspector in case user does not request these services.
This also removes cascade of some Conditions in Ironic controller. This allows us to make condition dependencies straight[1] and avoid non-straght ones[2].
[1]
Ironic.status.ReadyCondition
+-> IronicAPI.status.ReadyCondition
+-> IronicAPI.status.DeploymentReadyCondition
[2]
Ironic.status.ReadyCondition
+-> IronicAPI.status.ReadyCondition
|    +-> IronicAPI.status.DeploymentReadyCondition (*1)
+-> Ironic.Status.DeploymentReadyCondition
+-> IronicAPI.status.DeploymentReadyCondition (*1)
(*1) These two are same

Ensure all conditions are initialized

---

api/v1beta1/ironicneutronagent_types.go
config/crd/bases/ironic.openstack.org_ironicneutronagents.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml

Make `Secret` optional, and set omitempty to align with the other Kinds.

Align neutron-agent Secret with other types

---

api/v1beta1/ironicinspector_types.go
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml

ironic-inspector controller is not using this value but uses the secret internally created (via TransportURL CR).

IronicInspector: Remove unused spec.transportURLSecret

---

tests/functional/suite_test.go

... as we ensure the other CR schemas used by ironic-operator.

Ensure MariaDB/Galera CR Scheme in kuttl tests

---

api/v1beta1/funcs.go
api/v1beta1/ironic_types.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicconductor_types.go
api/v1beta1/ironicinspector_types.go
api/v1beta1/ironicneutronagent_types.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironicneutronagents.yaml
controllers/funcs.go
controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go
pkg/ironic/funcs.go
pkg/ironicapi/deployment.go
pkg/ironicconductor/statefulset.go
pkg/ironicinspector/dbsync.go
pkg/ironicinspector/statefulset.go
pkg/ironicneutronagent/deployment.go

Instead of requiering the ServiceAccount pre-created and defined in the Spec let each controller reconcile the ServiceAccount conditioned on owning Ironic existing.
When an owning Ironic instance exists, use the ServiceAccount created by the owner.

Service account - conditionally reconcile in all controllers

---

controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go

This ensures the controller watches service account, role, and role bindings to reconcile these resources in case any change is made.

Watch RBAC resources to trigger reconcile

---

controllers/ironic_controller.go

This was missed in:
https://github.com/openstack-k8s-operators/ironic-operator/pull/276

Fix keystoneVars for conductor

---

config/samples/ironic_v1beta1_ironic_conductor_groups.yaml
config/samples/ironic_v1beta1_ironic_standalone.yaml
config/samples/ironic_v1beta1_ironicapi.yaml
config/samples/ironic_v1beta1_ironicconductor.yaml
config/samples/ironic_v1beta1_ironicinspector.yaml
config/samples/ironic_v1beta1_ironicneutronagent.yaml

The issue with default Replicas spec has been resolved by [1], thus the replicas spec can be removed from samples now.
[1] c285e25b410a0ca7f81664072c33f0edb958d161

Drop hard-coded replicas from samples

---

controllers/ironic_controller.go
controllers/ironicconductor_controller.go
pkg/ironic/const.go
pkg/ironicapi/deployment.go
pkg/ironicapi/volumes.go
pkg/ironicconductor/const.go
templates/common/config/ironic.conf

This avoids permissions error when writing to /dev/stdout from a non-root user, which is an issue affecting OCP-4.13.x. Sidecar containers for API logging is the recommended pattern, has been done for some time by the nova-operator, and has just been implemented by cinder-operator[1]
[1] https://github.com/openstack-k8s-operators/cinder-operator/pull/238
Jira: [OSP-26868](https://issues.redhat.com//browse/OSP-26868)

Change ironic-api logging to using a sidecar container

---

api/v1beta1/conditions.go
controllers/ironic_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go
tests/functional/ironicinspector_controller_test.go
tests/functional/ironicneutronagent_controller_test.go

We have added the common RabbitMqTransportURLReady to lib-common to reduce duplicate implementations.
Depends-on: https://github.com/openstack-k8s-operators/lib-common/pull/300

Replace RabbitMqTransportURLReady by common condition

---

controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
pkg/ironic/dbsync.go
templates/ironic/bin/dbsync.sh

- Move dbsync to reconcileUpgrade
- Move dbsync to a dedicated script
- Run upgrade check before dbsync
- Use conductor container image for dbsync
- Wait 5 seconds between dbsync reconciles
- Run online_data_migrations after default dbsync
Jira: [OSP-22712](https://issues.redhat.com//browse/OSP-22712)

Extend dbsync to handle full update/upgrade

---

controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go

We don't have to update a CR when the CR does not contain the finalizer being removed. This also removes some unused/redundant function from the Reconciler struct.

Skip redundant update when removing a finalizer

---

api/v1beta1/ironic_webhook.go

ironic-neutron-agent should not be enabled when standalone mode is enabled. This introduces the validation at webhook.

Reject neutron agent in standalone mode

---

api/v1beta1/ironic_types.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicconductor_types.go
api/v1beta1/ironicinspector_types.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml

This adds the validation annotation so that the RPCTransport spec accepts a supported value.

Accept only supported values for RPCTransport

---

controllers/ironic_controller.go

Currently inspector, api and INA all log as
"Deployment ironic ... : created", change this to log the actual name of the deployment

Improve logging of deployments

---

Makefile

This updates the `manifests` Makefile target to copy config/crd/bases to /api on successful generation run.

Copy rendered CRD files dir to /api/bases in make manifests

---

pkg/ironicinspector/initcontainer.go
pkg/ironicinspector/statefulset.go
tests/functional/base_test.go

We need to run the ironic-python-agent-init container to copy the images to Inspectors http directory.

Run ironic-python-agent-init in Inspector

---

.github/create_bundle.sh
.prow_ci.env
api/v1beta1/ironic_types.go
config/default/manager_default_images.yaml
config/manifests/bases/ironic-operator.clusterserviceversion.yaml
tests/kuttl/common/assert-endpoints.yaml
tests/kuttl/tests/deploy/10-assert-deploy-ironic.yaml
tests/kuttl/tests/standalone/10-assert-deploy-ironic-standalone.yaml

This PR adds support for installing the operator in disconnected network environments. To build with image-digests set USE_IMAGE_DIGESTS=true before running make bundle.
For Prow jobs we are enabling this via .prow-ci.env
This drops the old logic from create_bundle.sh which has been broken with operator-sdk's make bundle for some time.
(NOTE: this currently requires a secure registry)

Support disconnected network environments

---

go.mod
go.sum
tests/functional/ironic_controller_test.go
tests/functional/ironicapi_controller_test.go
tests/functional/ironicconductor_controller_test.go
tests/functional/ironicinspector_controller_test.go
tests/functional/suite_test.go

This is necessary to remove a dependency cycle from lib-common

[envtest]Use database helpers from mariadb-operator

---

config/manifests/bases/ironic-operator.clusterserviceversion.yaml

This should hide the ironic package/bundle in the OpenShift console as we only want the main OpenStack operator to show up there.
NOTE: we may eventually make the Ironic project standalone but until then this should align ironic with other operators (hidden).

CSV: Set operator-type: non-standalone

---

controllers/ironic_controller.go
controllers/ironicinspector_controller.go
go.mod
go.sum

The lib-common/modules/database is moved to mariadb-operator/api to remove a circular dependency.

Use database helpers from mariadb-operator/api

---

controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go
main.go
tests/functional/suite_test.go

This automatically adds additional fields like reconcile_id etc.. from the controller context.
before :
`2023-05-18T01:53:14+03:00 INFO  controllers.KeystoneAPI Reconciled Service init successfully`
after:
`2023-10-19T11:33:31+03:00       INFO    Controllers.IronicNeutronAgent  Reconciled IronicNeutronAgent upgrade successfully      {"controller": "ironicneutronagent", "controllerGroup": "ironic.openstack.org", "controllerKind": "IronicNeutronAgent", "IronicNeutronAgent": {"name":"ironic-neutron-agent-sample","namespace":"openstack"}, "namespace": "openstack", "name": "ironic-neutron-agent-sample", "reconcileID": "957c9fcc-9ebc-4dc7-a077-31b8b7f1e8c0"}
`
*by using per reconcile function respective logger objects, the intention is to lay the ground for parallel reconciliation in future and …

switch to structured logging

---

templates/common/config/ironic.conf
tests/functional/base_test.go

This should fix ironic-operator-build-deploy-tempest which has failing tests due to incorrectly generated links[1].
[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_ironic-operator/355/pull-ci-openstack-k8s-operators-ironic-operator-main-ironic-operator-build-deploy-tempest/1722338128045281280/artifacts/ironic-operator-build-deploy-tempest/openstack-k8s-operators-tempest/artifacts/stestr_results.html

Set enable_proxy_headers_parsing=true

---

config/manifests/bases/ironic-operator.clusterserviceversion.yaml

Update to use new 'features.operators.openshift.io' annotations format for disconnected support
Jira: [OSP-30201](https://issues.redhat.com//browse/OSP-30201)

required infra annotations for OCP 4.14+

---

templates/ironicconductor/bin/pxe-init.sh
templates/ironicinspector/bin/pxe-init.sh
tests/functional/base_test.go

On RHEL-9.x the path is /boot/efi/EFI/redhat, not /boot/efi/EFI/rhel

Fix the boot EFI path for RHEL containers

---

templates/common/bin/common.sh
templates/common/config/ironic.conf
tests/functional/base_test.go
tests/functional/ironicapi_controller_test.go

enable use of service_user tokens role enforcement
This change also removes outdated todo comments
from the init container script.
As part of https://github.com/advisories/GHSA-fvf4-jv3j-73mq a hardening recommendation was made
to start enforce that the service token user must have the service
role. This change updates the ironic config to enable that enfrocement.
Closes: [OSPRH-3058](https://issues.redhat.com//browse/OSPRH-3058)
Closes: [OSPRH-191](https://issues.redhat.com//browse/OSPRH-191)

enable use of service_user tokens

---

Dockerfile

This is required for FIPS compliance as indicated by the check-payload tool[1]
[1] https://github.com/openshift/check-payload

Set CGO_ENABLED=1

---

templates/common/config/ironic.conf
templates/ironicinspector/config/inspector.conf

Upstream, Ironic has put forth a lot of work on improved policies, to improve security and overall capabilities. This change locks the default to use only the new policies which overall sets the most appropriate state for usage moving forward.

force rbac policy to only leverage the new policy

---

.prow_ci.env
Dockerfile
Makefile
config/manifests/bases/ironic-operator.clusterserviceversion.yaml

* Changed the build image to `ubi9/go-toolkit:1.20`
* Changed the base image to `ubi9/minimal`
* Added the default `GO_BUILD_EXTRA_ARGS="-tags strictfipsruntime"`
* Added the `GO_BUILD_EXTRA_ENV_ARGS` build argument to allow custom build arguments at build time. It defaults to `"CGO_ENABLED=1 GO111MODULE=on"`
* Those default parameters have been added to enable FIPS compliance
* Fixed indentation
* Added `DOCKER_BUILD_ARGS` variable in Makefile to pass custom parameters during `podman build`
* Added export `FAIL_FIPS_CHECK=true` to `prow_ci.env` file.
Closes: https://issues.redhat.com/browse/OSPRH-3102

This change ensures the `ironic-operator` is built with FIPS compliance

---

templates/common/config/ironic.conf

The ironic project shot down fixing "serivce" role support in older branches, so the only path forward is to explicitly set the option to be enabled by our operator.

fix: set rbac service role for services to operate properly

---

templates/common/config/ironic.conf

These were set to non-default values based on undercloud configuration, not overcloud. Defaults are more appropriate for a BMaaS service.

Use defaults for force_power_state_during_sync, automated_clean

---

controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go
go.mod
go.sum
templates/common/bin/common.sh
templates/ironic/config/db-sync-config.json
templates/ironicapi/config/ironic-api-config.json
templates/ironicconductor/config/ironic-conductor-config.json
templates/ironicinspector/config/db-sync-config.json
templates/ironicinspector/config/ironic-inspector-config.json
tests/functional/base_test.go
tests/functional/ironic_controller_test.go
tests/functional/ironicapi_controller_test.go
tests/functional/ironicconductor_controller_test.go
tests/functional/ironicinspector_controller_test.go

The my.cnf file gets added to the secret holding the service configs. The content of my.cnf is centrally managed in the mariadb-operator and retrieved calling db.GetDatabaseClientConfig(tlsCfg)
Depends-On: https://github.com/openstack-k8s-operators/mariadb-operator/pull/190
Depends-On: https://github.com/openstack-k8s-operators/mariadb-operator/pull/191
Jira: [OSPRH-4547](https://issues.redhat.com//browse/OSPRH-4547)

[tlse] TLS database connection

---

api/v1beta1/ironic_webhook.go

A follow up to allow the new IronicSpecCore to work with the webhook ValidateCreate and ValidationUpdate functions.
Jira: [OSPRH-4835](https://issues.redhat.com//browse/OSPRH-4835)

IronicSpecCore support for validation functions

---

api/v1beta1/ironic_webhook.go

Updates the function so that the type of the "old" and reciever are the same.

Correct ValidateUpdate for IronicSpecCore

---

pkg/ironicconductor/statefulset.go
pkg/ironicinspector/statefulset.go

Update the dnsmasq probe to check for IPv4 vs IPv6 DHCP ports in the probes based on what is configured in DHCPRanges.

Probe dnsmasq IPv4 vs IPv6 ports

---

.pre-commit-config.yaml
controllers/funcs.go
controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go
main.go
pkg/ironic/funcs.go
tests/functional/base_test.go
tests/functional/ironic_controller_test.go
tests/functional/ironicapi_controller_test.go
tests/functional/ironicconductor_controller_test.go
tests/functional/ironicinspector_controller_test.go
tests/functional/ironicneutronagent_controller_test.go
tests/functional/sample_test.go
tests/functional/suite_test.go

* removed unused func params and variables
* ignore revive dot-imports rule on ginkgo and gomega as dot import
there is the recommended practice
* various small style fixes found by the linter

Ensure golangci-lint runs on all files

---

api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
api/v1beta1/ironic_webhook.go
config/crd/bases/ironic.openstack.org_ironics.yaml

Right now applying a OpenStackControlPlane CR without any ironic section fails with:
~~~
$ oc apply -n openstack -f ...
The OpenStackControlPlane "openstack-galera-network-isolation-3replicas" is invalid:
* spec.ironic.template.rpcTransport: Unsupported value: "": supported values: "oslo", "json-rpc"
* spec.ironic.template.ironicConductors: Invalid value: "null": spec.ironic.template.ironicConductors in body must be of type array: "null" 
~~~
To allow the OpenstackControlPlane to be deployed without specifying any ironic there is the need to change the validation/defaulting of the RPCTransport and IronicConductors.
* RPCTransport The enum check is moved to the validations webhook for create and update, default set in the defaulting webhook.
* IronicConductors IronicConductors not longer a …

Move some validation from kubebuilder annotation to webhook

---

api/bases/ironic.openstack.org_ironicapis.yaml
api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironicinspectors.yaml
api/bases/ironic.openstack.org_ironicneutronagents.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicconductor_types.go
api/v1beta1/ironicinspector_types.go
api/v1beta1/ironicneutronagent_types.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironicneutronagents.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go
tests/functional/ironicapi_controller_test.go
tests/functional/ironicconductor_controller_test.go

This patch does a few things:
1. it adds `observedGeneration` to the sub custom resources
2. it proposes to bump the `observedGeneration` at the beginning of the reconciliation loop (knative/serving#4937)
3. it checks, at the top level, if the `observedGeneration` matches with the `metadata.generation` assigned to the `subCR(s)`; if it's the latest version, the condition is mirrored
4. before marking `DeploymentReadyCondition` as True in the `subCRs`, `observedGeneration` is compared with the `generation` of the `Deployment`/`Statefulset`
5. it updates the functional tests and bumps both `lib-common/modules/test` and `lib-common/modules/common`

Add ObservedGeneration to the sub Resources

---

pkg/ironicinspector/statefulset.go

With the default PodManagementPolicy: OrderedReadyPodManagement the statefulset controller will only progress pods when the previous/current pod is ready or terminated.
When service configuration changes while the pod is starting and the new configuration requires e.g. additional volume mounts the initial pod will never reach ready and therefore an update won't happen.
With ParallelPodManagement the statefulset controller will not wait for pods to be ready or complete termination.

 Use PodManagementPolicy: appsv1.ParallelPodManagement for statefulset

---

.pre-commit-config.yaml
tests/kuttl/common/assert-endpoints.yaml
tests/kuttl/tests/deploy_tls/10-assert-deploy-ironic.yaml

Kuttl only runs the last TestAssert in an assert file and silently
ignores the rest. So this patch combines the TestAsserts into a single
one with multiple commands listed.
Also to further secure against false positives set -euxo pipefail is
added to the scripts as well.
Also added a new pre-commit check to avoid this in the future.

[pre-commit][kuttl]Fix false positive asserts

---

controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go

Currently the reconciler returned both a non-zero result and a non-nil error.
The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff.
In case of NotFound return nil that the ReqeueAfter is used.
For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler

Return nil error in case NotFound and to use RequeueAfter

---

controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
pkg/ironicconductor/statefulset.go
pkg/ironicinspector/statefulset.go
templates/common/bin/runlogwatch.sh
templates/common/config/ironic.conf
templates/ironicconductor/bin/init.sh
templates/ironicconductor/config/ramdisk-logs-config.json
templates/ironicinspector/bin/init.sh
templates/ironicinspector/config/inspector.conf
templates/ironicinspector/config/ramdisk-logs-config.json
tests/functional/ironicconductor_controller_test.go
tests/functional/ironicinspector_controller_test.go

This implements the runlogwatch.sh approach of metal3[1] to write any deployment logs to the console, making them accessable to the end user via the same mechanism as other openstack service logs.
As part of this change the deploy logs directory needs to be moved to a directory on a volume shared by the pod. This is now /var/lib/ironic/ramdisk-logs
Jira: [OSPRH-1947](https://issues.redhat.com//browse/OSPRH-1947)
[1] https://github.com/metal3-io/ironic-image/blob/main/scripts/runlogwatch.sh

Add a ramdisk-logs sidecar

---

pkg/ironicapi/volumes.go

ironic-api-log is not currently logging anything because /var/log/ironic is not mounted into the ironic-api container. This change fixes that.
(cherry picked from commit 4597a402a7f2b1dbe76560d9a3def63fd7b4ca9a)
Jira: [OSPRH-10238](https://issues.redhat.com//browse/OSPRH-10238)

Add missing log mount to ironic-api

---

controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go

It is hidden right now if there is an error in configured named fields and index. Lets log the error and return the current state of requests.
With this the findObjectsForSrc() will exit with an hidden error like:
```
"error": "Index with name field:.spec.ksmTls.caBundleSecretName does not exist"
```

Make sure to log error in findObjectsForSrc()

---

templates/common/config/ironic.conf

Dracclient has been removed from the container images[1] and
ironic-conductor will not start if wsman drivers are in then enabled
list. This change removes them.
[1] https://github.com/openstack-k8s-operators/tcib/pull/224
Jira: [OSPRH-11193](https://issues.redhat.com//browse/OSPRH-11193)

Remove idrac-wsman drivers from configured list

---

templates/common/config/ironic.conf

The default interface parameter inadvertently set the default for all newly created nodes, unless they otherwise specify a network interface, to be "noop", which is only usable for standalone users.
Integrated users want flat, or neutron. Given historical usage pattern, the existing defaults set via "enabled_network_interfaces" to use flat, neutron, or noop, in that order, are generally applicable.
Jira: [OSPRH-10697](https://issues.redhat.com//browse/OSPRH-10697)

Fix default network interface

---

api/v1beta1/common_types.go
api/v1beta1/ironic_types.go
api/v1beta1/ironicinspector_types.go
api/v1beta1/zz_generated.deepcopy.go
controllers/ironic_controller.go
pkg/ironic/dbsync.go
pkg/ironicapi/deployment.go
pkg/ironicconductor/statefulset.go
pkg/ironicinspector/dbsync.go
pkg/ironicinspector/statefulset.go
pkg/ironicneutronagent/deployment.go
tests/functional/base_test.go
tests/functional/ironic_controller_test.go

nodeSelectors are not currently applied consistently across all operators.
Some do not support nodeSelectors at all - will be implemented in this series of pull requests.
Some do not apply them to every pod (jobs/cronjobs esp) - will be resolved in this series of pull requests.
Some do not apply a node selector update correctly, only when not initially set.
Some support nodeSelectors but do not inherit the default nodeSelector from the OpenstackControlPlane CR.
Jira: [OSPRH-10734](https://issues.redhat.com//browse/OSPRH-10734)

Ensure nodeSelector logic is consistent for all operators

---

templates/ironicapi/config/ironic-api-httpd.conf
templates/ironicinspector/config/httpd.conf

- Fix httpd RequestHeader setting for non-TLS deployment
- Update comment pointing to RequestHeader directive syntax
Jira: [OSPRH-12377](https://issues.redhat.com/browse/OSPRH-12377)

Fix httpd config for X-Forwarded-Proto Jira: <OSPRH-12377>

---

templates/common/bin/pxe-init.sh

Currently the pxe-init script copies the certificate bundle directly to `/etc/pki/ca-trust/extracted `in the initramfs. When `update-ca-trust` runs under chroot the contents under `pki/ca-trust/extracted` is overwritten. See manual page: update-ca-trust(8) "EXTRACTED CONFIGURATION" section.
With this change the bundle is copied to `/etc/pki/ca-trust/source/anchor`s directory in the initramfs instead, so that `update-ca-trust` will find the source and update CA certs and trusts correctly.
Jira: [OSPRH-12526](https://issues.redhat.com//browse/OSPRH-12526)

Fix ironic-python-agent - CA bundle inject

---

api/bases/ironic.openstack.org_ironicapis.yaml
api/bases/ironic.openstack.org_ironicinspectors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
api/v1beta1/ironic_webhook.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicinspector_types.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicinspector_controller.go
templates/ironicapi/config/ironic-api-httpd.conf
templates/ironicinspector/config/httpd.conf

- Added apiTimeout property to ironic api with default set to 60 seconds
Jira: [OSPRH-10958](https://issues.redhat.com/browse/OSPRH-10958)

Add configurable API Timeouts <JIRA: OSPRH-10958>

---

api/v1beta1/ironic_webhook.go

The openstack-operators repository only makes use of the IronicSpecCore type in its template. As a result, the method name and arguments have to be changed. 
Jira: [OSPRH-10958](https://issues.redhat.com/browse/OSPRH-10958)

Change Route Annotation method name and argument for spec <JIRA: OSPRH-10958>

---

controllers/ironicconductor_controller.go
pkg/ironicconductor/statefulset.go

The `resource.MustParse` function was previously used by the operator to process the `storageSize` request provided by the top-level CR. However, even though `defer()` and `recover()` can be used to handle the `panic()` generated by  the wrong user input, that approach doesn't seem to work properly and the operator crashes without any chance to recover. The `ParseQuantity` implementation returns an `error` instead of `panic()`, and it can be easily caught at the operator level. This change moves away from the `MustParse` usage and relies on the `ParseQuantity` mechanism.

Do not use MustParse to process PVC size

---

templates/common/bin/pxe-init.sh

Prints an info message to be displayed if `dd`, `mkfs.msdos` or `mmd` are missing
Jira: [OSPRH-14452](https://issues.redhat.com/browse/OSPRH-14452)

Fix init container crashloop <JIRA-14452>

---

tests/functional/base_test.go
tests/functional/ironic_controller_test.go

This patch improves our topology testing with several enhancements and extends the `topologyRef` tests:
- `finalizer` verification for each sub component that references a topology
- Updated `Topologies` to support `component-specific` label selectors
This work completes the topology validation improvements initiated in [1], addressing the remaining open points.
Jira: https://issues.redhat.com/browse/OSPRH-15220
[1] nova-operator#941

Improve topology testing coverage

---

api/go.mod
api/go.sum
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go
go.mod
go.sum
tests/functional/ironic_controller_test.go

Changes to use the common IsReady() func to validate a deployment is fully up as requested and e.g. no update rollout in progress. During a minor update this has seen to already report/mark the condition ready, even the deployment is still in progress, or the replacement pod failed.
Jira: [OSPRH-14472](https://issues.redhat.com//browse/OSPRH-14472)
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/616

Use deployment.IsReady() to validate status

---

api/go.mod
api/go.sum
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go
go.mod
go.sum
tests/functional/ironic_controller_test.go

Changes to use the common IsReady() func to validate a deployment is fully up as requested and e.g. no update rollout in progress. During a minor update this has seen to already report/mark the condition ready, even the deployment is still in progress, or the replacement pod failed.
Jira: [OSPRH-14472](https://issues.redhat.com//browse/OSPRH-14472)
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/619
Signed-off-by: Martin Schuppert <mschuppert@redhat.com>
(cherry picked from commit 3d345b4b74537e685f84e20b4cef9e4b5ed18213)

[18.0-fr2] Use deployment.IsReady() to validate status

---

templates/ironicinspector/bin/inspector-pxe-init.sh

When running `envsubst $file` and pipe to `tee $file` there is a race causing the target file to be wiped.
The following script can be used to reproduce the race condition:
```
#!/bin/sh
echo -e "foo\nbar\nbaz" > /tmp/test_file
count=0
while [ -s /tmp/test_file ]; do
envsubst < /tmp/test_file | tee /tmp/test_file > /dev/null
((count+=1))
done
if [ ! -s /tmp/test_file ]; then
echo "File was wiped after $count run's of:  envsubst < \$file | tee \$file"
fi
```
```
$ sh test.sh
File was wiped after 16 run's of:  envsubst < $file | tee $file
$ sh test.sh
File was wiped after 42 run's of:  envsubst < $file | tee $file
$ sh test.sh
File was wiped after 37 run's of:  envsubst < $file | tee $file
$ sh test.sh
File was wiped after 73 run's of:  envsubst < $file | tee $file
$ sh test.sh
File was …
```

Fix race condition - envsubst $file | tee $file

---

controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go

Continuation of commit: https://github.com/openstack-k8s-operators/ironic-operator/pull/570
In commit: https://github.com/openstack-k8s-operators/ironic-operator/commit/95b3db1372ff5f588fcb87e70fafe8ef319ad374 there was a switch
from using ConfigMap to using secret.
```
-       return configmap.EnsureConfigMaps(ctx, h, instance, cms, envVars)
+       return secret.EnsureSecrets(ctx, h, instance, cms, envVars)
```
In this PR:
- configMapFn is residual code and can be removed because the return is secret and not configmap. 
- make ironic-api and ironic-conductor pods reboot when changes are made to the base level customServiceConfig configuration. 
Jira: [OSPRH-10696](https://issues.redhat.com/browse/OSPRH-10696)

Remove configMapFn and refactor findObjectsForSrc <JIRA: OSPRH-10696>

---

controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
templates/common/bin/common.sh
templates/ironic/bin/dbsync.sh
templates/ironic/config/db-sync-config.json
templates/ironicapi/config/ironic-api-config.json
templates/ironicconductor/config/ironic-conductor-config.json

With the changes in https://github.com/openstack-k8s-operators/ironic-operator/pull/573, the conductor and api pods restart when a change is made to `ironic.template.customServiceConfig`. But the config in `ironic.ironicAPI.customServiceConfig` and `ironic.ironicConductor.customServiceConfig` do not override the base level config. This PR renames the custom.conf file so it is loaded in later and overrides the config. 
Jira: [OSPRH-10696](https://issues.redhat.com/browse/OSPRH-10696)

Override base level customServiceConfig in api and conductor <JIRA: OSPRH-10696>

---

controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
pkg/ironicconductor/volumes.go
templates/common/config/ironic.conf
templates/ironic/config/db-sync-config.json
templates/ironicapi/config/ironic-api-config.json
templates/ironicconductor/bin/init.sh
templates/ironicconductor/config/01-conductor.conf
templates/ironicconductor/config/03-init-container-conductor.conf
templates/ironicconductor/config/dnsmasq-config.json
templates/ironicconductor/config/httpboot-config.json
templates/ironicconductor/config/ironic-conductor-config.json
tests/functional/ironicconductor_controller_test.go

Reverts https://github.com/openstack-k8s-operators/ironic-operator/pull/589 and also effects https://github.com/openstack-k8s-operators/ironic-operator/pull/585 again with some changes to fix improper configurations on it which caused tempest tests to fail.
- A new init conf has been created for conductor-init for the init pod, this will be populated with values from the init.sh command and uses crudini. The passwords are made more secure by staying in Kubernetes secrets instead of storing it in ConfigMaps using `templateParameters`
- crudini usage for merging in files together has been reduced
- 01-conductor.conf has been created to house the conductor configuration with some barebones configuration
- 
Jira: [OSPRH-18581](https://issues.redhat.com/browse/OSPRH-18581)

Refactor ironic-conductor to use --config-dir <JIRA: OSPRH-18581>

---

controllers/ironicapi_controller.go
pkg/ironicapi/deployment.go
pkg/ironicapi/volumes.go
templates/ironicapi/config/01-api.conf
templates/ironicapi/config/ironic-api-config.json

With refactors in ironic-api and ironic-conductors configuration, the common.sh and ironic-init.sh files are not being used anymore to merge configuration using crudini. As a result, they can be removed from the repository and links to them can also be removed. 
Jira: [OSPRH-18581](https://issues.redhat.com/browse/OSPRH-18581)

Remove redundant scripts <JIRA: OSPRH-18581>

---

controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicneutronagent_controller.go

Removes no-op reconcileUpdate/reconcileUpgrade functions from controllers. 
Jira: [OSPRH-18886](https://issues.redhat.com/browse/OSPRH-18886)

Remove no-op reconcile functions from controllers <JIRA: OSPRH-18886>

---

controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
templates/common/config/ironic.conf
templates/ironicapi/config/01-api.conf

Fixes an issue where `rpc_transport` is not set to `oslo` even if instance.Spec.RPCTransport is `oslo`. This caused the service to try to connect using json-rpc, which failed because json-rpc service service is only exposed when RPC Transport is json-rpc.
Set rpc_transport to match instance.Spec.RPCTransport.
Jira: [OSPRH-19936](https://issues.redhat.com//browse/OSPRH-19936)
Jira: <OSPRH link>

Ensure rpc_transport is set in ironic.conf

---

api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
api/v1beta1/ironic_webhook.go
api/v1beta1/ironicconductor_types.go
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml

This change introduces the CRD changes for the feature flag and new images required for graphical consoles.
This is required to add without any backing implementation so that openstack-operator can pull in the CRD changes and establish the CSV entries for overriding the images.
The feature flag will remain false until RHOSO-19 and this will never work with default antelope images.
Jira: [OSPRH-20211](https://issues.redhat.com//browse/OSPRH-20211)

CRD changes for graphical console

---

templates/ironicconductor/bin/init.sh
templates/ironicinspector/bin/inspector-pxe-init.sh
templates/ironicinspector/config/dnsmasq.conf
templates/ironicinspector/config/inspector.ipxe

The init scripts for ironic conductor and inspector need to detect IPv6 and format the http and tftp URL's accordingly.
Fixes: [OSPRH-20483](https://issues.redhat.com//browse/OSPRH-20483)

Fix IPv6 URL formatting in init scripts
