.github/dependabot.yml
Makefile
api/v1beta1/ironic_types.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicconductor_types.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
config/samples/ironic_v1beta1_ironic_standalone.yaml
controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/suite_test.go
pkg/ironic/const.go
pkg/ironicapi/deployment.go
pkg/ironicconductor/service.go
templates/ironic/config/ironic.conf

It is now possible to create ironic nodes using hardware type fake-hardware

Improve keystone integration, fix api->conductor communication

---

.github/workflows/golangci-lint.yaml
.gitignore
Makefile
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_types.go
config/crd/bases/ironic.openstack.org_ironics.yaml

1. ensure that normal linting runs on the `api` module as well
2. introduce operator-lint [1] make target and run it in github workflow to check for operator development specific rule violations.
3. fix such violations
[1] https://github.com/gibizer/operator-lint

Lint improvements

---

config/samples/ironic_v1beta1_ironic.yaml
config/samples/ironic_v1beta1_ironic_standalone.yaml
templates/ironic/bin/imagetter.yaml

This aligns with all other operators

Switch from master to zed for ironic images

---

controllers/ironicconductor_controller.go
pkg/ironicconductor/service.go

Only create json-rpc service if RPCTransport is json-rpc.

Refactor conductor service creation

---

controllers/ironicinspector_controller.go

Implement reconcileServices in ironicinspector controller in the same way it is implemented in ironicconductor.

Configure inspector services

---

.github/workflows/build-ironic-operator.yaml
Dockerfile
Makefile
api/bases/ironic.openstack.org_ironicapis.yaml
api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironicinspectors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/go.mod
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
config/manifests/bases/ironic-operator.clusterserviceversion.yaml
go.mod

Based on https://github.com/openstack-k8s-operators/nova-operator/commit/a1d25dd54944e30383c40e11ad979cedf5f59cb0

Bump to golang 1.19 and SDK 1.26

---

controllers/ironic_controller.go
controllers/ironicinspector_controller.go
pkg/ironic/funcs.go

Makes a shared TransportURLCreateOrUpdate function in funcs.go to replace the duplicate function in ironic an inspector controllers.

Shared TransportURLCreateOrUpdate - pkg/ironic/funcs.go

---

.github/create_bundle.sh
.github/workflows/build-ironic-operator.yaml
Makefile

Don't use the environment's operator-sdk, it could be any version

Use local operator-sdk

---

go.mod
go.sum
main.go
pkg/ironic/funcs.go

This cyclic dep is probably breaking the jobs.

Use infra-operator

---

controllers/ironicinspector_controller.go

This is just restructuring the code, splitting reconcileNormal, reconcileInit and reconcileDelete into smaller functions.

Inspector reconcilers split up

---

.ci-operator.yaml

Added ci-operator.yml to use build_root_image
config in prow jobs.

Added ci-operator.yml

---

api/v1beta1/ironic_webhook.go

Reject create/update request if IronicConducts elements with duplicate ConductorGroup exists in the Ironic Spec.
Jira: [OSP-22448](https://issues.redhat.com//browse/OSP-22448)

Webhook - Validate ConductorGroup is unique

---

api/v1beta1/conditions.go

Remove "Condition" from the end of IronicInspectorReadyCondition, to align with other Ready conditions.

Change IronicInspectorReadyCondition value

---

controllers/ironic_controller.go

Compilation is currently failing with the error:
controllers/ironic_controller.go:506:27: undefined: ironicInspector because ironicInspector is being accessed outside the block which assigns it.
This change reworks the ready boolean checks to initialize them early and change them in context.

Fix compilation of ready boolean checks

---

tests/kuttl/common/assert-sample-deployment.yaml

Change-Id: Icaf216fa0eb0e36589216d4be77a9303fc19c18e

Add endpoint validation kuttl tests

---

tests/kuttl/common/assert-sample-deployment.yaml

Change-Id: I38a3dfe844428e98968e11f61b69f82059cb950f

Use Regex to get endpoints to validate

---

api/bases/ironic.openstack.org_ironicapis.yaml
api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironicinspectors.yaml
api/bases/ironic.openstack.org_ironics.yaml
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml

Regenerate to update descriptions after bumping dependencies.

Regenerate manifests

---

api/bases/ironic.openstack.org_ironicapis.yaml
api/bases/ironic.openstack.org_ironicconductors.yaml
api/bases/ironic.openstack.org_ironicinspectors.yaml
api/bases/ironic.openstack.org_ironics.yaml
api/v1beta1/ironic_webhook.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicconductor_types.go
api/v1beta1/ironicinspector_types.go
api/v1beta1/webhook_suite_test.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml
main.go

Adds webhook functional tests that were missing from scaffolding. Also makes minor improvement tweaks to webhooks and defaults based on further feedback on our general webhook pattern.

Webhook improvements

---

controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
pkg/ironic/const.go
pkg/ironicconductor/pvc.go

... instead of re-defining the same.

Use ComponentSelector in lib-common

---

api/v1beta1/ironic_webhook.go

The pattern is documented in https://github.com/openstack-k8s-operators/docs/pull/47

Align to validation webhook pattern

---

Makefile
config/samples/ironic_v1beta1_ironic.yaml
config/samples/ironic_v1beta1_ironic_conductor_groups.yaml
config/samples/ironic_v1beta1_ironic_standalone.yaml
config/samples/ironic_v1beta1_ironicapi.yaml
config/samples/ironic_v1beta1_ironicconductor.yaml
config/samples/ironic_v1beta1_ironicinspector.yaml
config/samples/ironic_v1beta1_ironicneutronagent.yaml
controllers/ironicinspector_controller.go
tests/functional/base_test.go
tests/functional/ironicinspector_controller_test.go
tests/functional/sample_test.go
tests/functional/suite_test.go

* Add more test scaffoling
* Cover more config samples
* Add tests for inspector controller

Add more EnvTest coverage

---

api/v1beta1/ironic_types.go
api/v1beta1/ironicapi_types.go
api/v1beta1/ironicconductor_types.go
api/v1beta1/ironicinspector_types.go
config/crd/bases/ironic.openstack.org_ironicapis.yaml
config/crd/bases/ironic.openstack.org_ironicconductors.yaml
config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
config/crd/bases/ironic.openstack.org_ironics.yaml

This ensures we mention the correct service according to CR.

Fix wrong service mentioned in spec descriptions

---

tests/kuttl/tests/deploy/10-assert-deploy-ironic.yaml
tests/kuttl/tests/deploy/20-assert-deploy-ironic-conductor-groups.yaml

Assert the Ironic Neutron Agent deployment in kuttl test.

Add validation of Ironic Neutron Agent to kuttl test

---

pkg/ironicinspector/statefulset.go

Formating nit in pkg/ironicinspector/statefulset.go

Fix formating with "make fmt"

---

tests/functional/base_test.go
tests/functional/ironic_controller_test.go
tests/functional/suite_test.go

Initial EnvTest coverage for the ironic controller

Add tests for ironic controller

---

config/samples/ironic_v1beta1_images.yaml
config/samples/kustomization.yaml

Jira: [OSP-30111](https://issues.redhat.com//browse/OSP-30111)

Drop container images from config/samples

---

Makefile

specify version for operator-sdk for make bundle
download operator-sdk pinned version when generating bundle update make bundle to use local operator-sdk
update to 1.31 version

update operator-sdk to local bin

---

config/default/manager_default_images.yaml

Jira: [OSPRH-4220](https://issues.redhat.com//browse/OSPRH-4220)

Revert ironic-inspector default image

---

pkg/ironicconductor/pvc.go

This reverts commit 30184808a78ebc6783ab415c5896b1a82fe4f999.

Revert "Fix VolumeResourceRequirements"

---

tests/functional/base_test.go

Issue seen in CI, looks like a race where the fake CRD is not yet present when trying to set up the fake ingress controller.
Add an eventually after creating the fake CRD.

Add eventually to wait for fake ingresscontrollers CRD

---

zuul.d/projects.yaml

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1163
Depends-On: https://github.com/openstack-k8s-operators/ironic-operator/pull/397

Enable podified zuul jobs against Ironic operator

---

templates/ironicinspector/config/inspector.conf

jira: https://issues.redhat.com/browse/OSPRH-5435

Change inspector listen_address for ipv6

---

pkg/ironicconductor/statefulset.go
pkg/ironicinspector/statefulset.go

dnsmasq is used for DHCP and TFTP. TFTP is always enabled, but DHCP is only enabled if DHCPRanges is defined. The probes for liveness and readuness fail when DHCPRanges is not defined.
Add a condition, and only probe for port 69 (tftp) when DHCPRanges are not configured.

Fix dnsmasq probes when no DHCPRanges defined

---

config/manifests/bases/ironic-operator.clusterserviceversion.yaml

recent changes didn't update the CSV yaml file.
This updates to match what make bundle modifies things with

update CSV with tls

---

config/manifests/bases/ironic-operator.clusterserviceversion.yaml

Issue: [OSPRH-7888](https://issues.redhat.com//browse/OSPRH-7888)

Add Required Infrastructure Annotations to CSV

---

config/rbac/role.yaml
controllers/ironic_controller.go
controllers/ironicapi_controller.go
controllers/ironicconductor_controller.go
controllers/ironicinspector_controller.go
controllers/ironicneutronagent_controller.go

We also took the opportunity and added patch to all the existing rbac rules that had update already to avoid similar issues in the future
Resolves: https://issues.redhat.com/browse/OSPRH-8363

Adding patch rbac perm for serviceaccounts

---

tests/functional/base_test.go

The job openstack-k8s-operators-content-provider is very unstable because fetching all api resources sometimes returns a 404, which is presumably a transient error which happens early in the cluster's life.
This change attempts to mitigate this by having a custom CreateUnstructured which wraps the CreateOrPatch in an Eventually.

functional test use a retrying CreateUnstructured

---

config/manifests/bases/ironic-operator.clusterserviceversion.yaml

Jira: [OSPRH-8830](https://issues.redhat.com//browse/OSPRH-8830)

Remove deprecated infrastructure-features annotation

---

templates/common/bin/runlogwatch.sh

This aligns with metal3 runlogwatch.sh[1] which is possible now that inotify-tools package is available[2].
[1] https://github.com/metal3-io/ironic-image/pull/548/files
[2] https://github.com/openstack-k8s-operators/tcib/commit/0795bb902af2199905413cae8593d382618459e8
Jira: [OSPRH-10240](https://issues.redhat.com//browse/OSPRH-10240)

Convert runlogwatch.sh to use inotifywait

---

tests/functional/ironic_controller_test.go

Related: [OSPRH-14494](https://issues.redhat.com//browse/OSPRH-14494)

[functional] verify LastAppliedTopology != nil before checking name

---

pkg/ironicapi/deployment.go
pkg/ironicapi/volumes.go
pkg/ironicconductor/statefulset.go
pkg/ironicconductor/volumes.go
tests/functional/ironicapi_controller_test.go
tests/functional/ironicconductor_controller_test.go

Jira: [OSPRH-10696](https://issues.redhat.com/browse/OSPRH-10696)

Change volumes.go to use parentName for secret <JIRA: OSPRH-10696>
